name: Test Build Container Image

on:
  pull_request:
    branches:
      - master

jobs:
  test_build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Get version
      run: echo "IMAGE_TAG=${GITHUB_ACTOR}" >> $GITHUB_ENV


    - name: Build Docker Image
      run: docker build -t ghcr.io/${GITHUB_REPOSITORY}:${IMAGE_TAG} .